# Generated by Django 2.0.2 on 2018-02-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20180224_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='desc',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(default='NULL'),
        ),
    ]
