# Generated by Django 2.0.2 on 2018-02-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20180224_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
